Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/bionic64"
  # config.vm.box = "ubuntu/focal64"
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.linked_clone = true
  end

  config.vm.define "manager" do |manager|
    manager.vm.network :private_network, ip: "192.168.56.2"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.network :private_network, ip: "192.168.56.3"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.network :private_network, ip: "192.168.56.4"
  end

  ssh_pub_key = File.readlines("/home/sgnd/.ssh/id_rsa.pub").first.strip

  config.vm.provision "shell", inline: <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
  SHELL
end